# Generated by Django 5.2.4 on 2025-08-02 09:12

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Required. Enter a valid email address.', max_length=254, unique=True, verbose_name='Email address')),
                ('name', models.CharField(help_text='Enter your full name.', max_length=100, verbose_name='Full name')),
                ('avatar', models.ImageField(blank=True, help_text='Upload a profile picture (optional).', null=True, upload_to='avatars/', verbose_name='Profile picture')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself (optional).', max_length=500, verbose_name='Bio')),
                ('website', models.URLField(blank=True, help_text='Your personal website (optional).', verbose_name='Website')),
                ('twitter', models.URLField(blank=True, help_text='Your Twitter profile URL (optional).', verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, help_text='Your LinkedIn profile URL (optional).', verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, help_text='Your GitHub profile URL (optional).', verbose_name='GitHub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
